### PR TITLE
Add Open File Button, Fix Unescaped Filename in Notifications, Fix GTK Crashing

### LINKED ISSUE #114: Add OpenFile Button When Download Done
Add a button to allow the user to open the file directly, as well as still provide the option to open the save folder itself.

### LINKED ISSUE #129: Issues with Youtube Music Playlists
Hey I just wanted to report that it has issues downloading Youtube Music playlists and hoping this could get fixed.

Currently if I try and download a playlist, even one with only 22 songs it will just sit there loading than eventually crash

image

### LINKED ISSUE #130: UI hangs and then closes itself
While downloading playlist the UI hangs and then quits.

I'm running Flatpak version 2023.3.1(but this has been happening in previous versions also) in PoP_OS 22.04.

This are some logs I've been gathering:

This one closed after loading the playlist but before downloading anything
```
(NickvisionTubeConverter.GNOME:2): Gtk-CRITICAL **: 12:42:39.313: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed
(NickvisionTubeConverter.GNOME:2): Gtk-CRITICAL **: 12:42:39.313: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
```

This one closed after downloading more or less ten videos
```
(NickvisionTubeConverter.GNOME:2): Gtk-CRITICAL **: 12:52:39.722: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionTubeConverter.GNOME:2): Gtk-CRITICAL **: 12:52:39.722: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 12:55:34.121: pango_layout_set_attributes: assertion 'layout != NULL' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 12:55:34.121: pango_layout_set_alignment: assertion 'layout != NULL' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 12:55:34.121: pango_layout_set_ellipsize: assertion 'PANGO_IS_LAYOUT (layout)' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 12:55:34.121: pango_layout_set_wrap: assertion 'PANGO_IS_LAYOUT (layout)' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 12:55:34.121: pango_layout_set_single_paragraph_mode: assertion 'PANGO_IS_LAYOUT (layout)' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 12:55:34.121: pango_layout_set_tabs: assertion 'PANGO_IS_LAYOUT (layout)' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 12:55:34.121: pango_layout_get_width: assertion 'layout != NULL' failed

(NickvisionTubeConverter.GNOME:2): GLib-GObject-CRITICAL **: 12:55:34.121: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 12:55:34.121: pango_layout_set_width: assertion 'layout != NULL' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 12:55:34.121: pango_layout_get_extents: assertion 'layout != NULL' failed

(NickvisionTubeConverter.GNOME:2): GLib-GObject-CRITICAL **: 12:55:34.121: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(NickvisionTubeConverter.GNOME:2): GLib-CRITICAL **: 12:57:15.915: Source ID 53391 was not found when attempting to remove it
Process terminated. A callback was made on a garbage collected delegate of type 'NickvisionTubeConverter.GNOME!NickvisionTubeConverter.GNOME.Controls.DownloadRow+GSourceFunc::Invoke'.
Repeat 2 times:
--------------------------------
   at Gio.Internal.Application.Run(IntPtr, Int32, System.String[])
--------------------------------
   at Gio.Application.Run(Int32, System.String[])
   at NickvisionTubeConverter.GNOME.Program.Run(System.String[])
   at NickvisionTubeConverter.GNOME.Program.Main(System.String[])
```

### LINKED ISSUE #152: Unescape filenames in notifications and in logs
Since fixing #141 filenames are now unescaped after downloading, but they are still shown escaped in notifications, and there's no message in logs that unescaping happened.

### LINKED ISSUE #156: The latest version fails to download webm in worst quality
## Steps to reproduce

1. Open Tube Converter.
2. Click "Add Download".
3. Paste this link: https://www.youtube.com/watch?v=UIp6_0kct_U and click "Validate URL".
4. Set File Type to WEBM, Quality to Worst, Subtitle to SRT.
5. Click "Download" and wait.

settings

## Expected behavior

File is downloaded successfully.

## Actual behavior

When the download process reaches 100%, it errors.

Screenshot from 2023-04-03 22-17-04

<details><summary>Logs</summary>

```log
youtube] Extracting URL: https://www.youtube.com/watch?v=UIp6_0kct_U
[youtube] UIp6_0kct_U: Downloading webpage
[youtube] UIp6_0kct_U: Downloading android player API JSON
[info] UIp6_0kct_U: Downloading 1 format(s): 17
[download] Destination: /home/khai/.var/app/org.nickvision.tubeconverter/config/Nickvision/Nickvision Tube Converter/temp/c22ae8d1-07f2-466f-8412-0244cf492794/WE\ ARE\ JAPANESE\ GOBLIN\ \[MMD]\.3gp

[download]   0.0% of    2.24MiB at    2.68KiB/s ETA 14:13
[download]   0.1% of    2.24MiB at    7.94KiB/s ETA 04:48
[download]   0.3% of    2.24MiB at   18.45KiB/s ETA 02:03
[download]   0.7% of    2.24MiB at   39.38KiB/s ETA 00:57
[download]   1.4% of    2.24MiB at   29.68KiB/s ETA 01:16
[download]   2.4% of    2.24MiB at   20.52KiB/s ETA 01:48
[download]   3.0% of    2.24MiB at   18.34KiB/s ETA 02:01
[download]   3.6% of    2.24MiB at   17.64KiB/s ETA 02:05
[download]   4.3% of    2.24MiB at   17.43KiB/s ETA 02:05
[download]   5.0% of    2.24MiB at   17.96KiB/s ETA 02:01
[download]   5.9% of    2.24MiB at   18.77KiB/s ETA 01:54
[download]   7.0% of    2.24MiB at   18.05KiB/s ETA 01:57
[download]   7.6% of    2.24MiB at   19.73KiB/s ETA 01:47
[download]   9.0% of    2.24MiB at   19.49KiB/s ETA 01:47
[download]   9.7% of    2.24MiB at   19.55KiB/s ETA 01:45
[download]  10.6% of    2.24MiB at   18.44KiB/s ETA 01:51
[download]  11.1% of    2.24MiB at   19.29KiB/s ETA 01:45
[download]  12.1% of    2.24MiB at   18.69KiB/s ETA 01:47
[download]  12.7% of    2.24MiB at   18.51KiB/s ETA 01:48
[download]  13.4% of    2.24MiB at   18.44KiB/s ETA 01:47
[download]  14.1% of    2.24MiB at   18.64KiB/s ETA 01:45
[download]  15.2% of    2.24MiB at   18.99KiB/s ETA 01:42
[download]  16.3% of    2.24MiB at   18.72KiB/s ETA 01:42
[download]  17.0% of    2.24MiB at   18.67KiB/s ETA 01:41
[download]  17.7% of    2.24MiB at   18.71KiB/s ETA 01:40
[download]  18.6% of    2.24MiB at   18.90KiB/s ETA 01:38
[download]  19.6% of    2.24MiB at   18.54KiB/s ETA 01:39
[download]  20.2% of    2.24MiB at   19.11KiB/s ETA 01:35
[download]  21.5% of    2.24MiB at   18.98KiB/s ETA 01:34
[download]  22.2% of    2.24MiB at   18.98KiB/s ETA 01:33
[download]  23.0% of    2.24MiB at   19.05KiB/s ETA 01:32
[download]  23.9% of    2.24MiB at   18.70KiB/s ETA 01:33
[download]  24.5% of    2.24MiB at   18.57KiB/s ETA 01:33
[download]  25.1% of    2.24MiB at   19.05KiB/s ETA 01:30
[download]  26.4% of    2.24MiB at   18.97KiB/s ETA 01:28
[download]  27.2% of    2.24MiB at   18.98KiB/s ETA 01:27
[download]  28.0% of    2.24MiB at   18.61KiB/s ETA 01:28
[download]  28.5% of    2.24MiB at   18.94KiB/s ETA 01:26
[download]  29.5% of    2.24MiB at   18.66KiB/s ETA 01:26
[download]  30.1% of    2.24MiB at   18.64KiB/s ETA 01:25
[download]  30.8% of    2.24MiB at   18.67KiB/s ETA 01:24
[download]  31.7% of    2.24MiB at   18.75KiB/s ETA 01:23
[download]  32.7% of    2.24MiB at   18.95KiB/s ETA 01:21
[download]  34.0% of    2.24MiB at   18.88KiB/s ETA 01:20
[download]  34.7% of    2.24MiB at   18.86KiB/s ETA 01:19
[download]  35.5% of    2.24MiB at   18.91KiB/s ETA 01:18
[download]  36.4% of    2.24MiB at   18.67KiB/s ETA 01:17
[download]  37.0% of    2.24MiB at   18.95KiB/s ETA 01:16
[download]  38.1% of    2.24MiB at   18.79KiB/s ETA 01:15
[download]  38.7% of    2.24MiB at   18.81KiB/s ETA 01:14
[download]  39.6% of    2.24MiB at   18.87KiB/s ETA 01:13
[download]  40.6% of    2.24MiB at   18.69KiB/s ETA 01:12
[download]  41.1% of    2.24MiB at   18.96KiB/s ETA 01:11
[download]  42.3% of    2.24MiB at   18.82KiB/s ETA 01:10
[download]  43.0% of    2.24MiB at   18.81KiB/s ETA 01:09
[download]  43.8% of    2.24MiB at   18.86KiB/s ETA 01:08
[download]  44.7% of    2.24MiB at   18.68KiB/s ETA 01:07
[download]  45.3% of    2.24MiB at   18.92KiB/s ETA 01:06
[download]  46.4% of    2.24MiB at   18.83KiB/s ETA 01:05
[download]  47.1% of    2.24MiB at   18.81KiB/s ETA 01:04
[download]  47.9% of    2.24MiB at   18.82KiB/s ETA 01:03
[download]  48.8% of    2.24MiB at   18.92KiB/s ETA 01:02
[download]  49.9% of    2.24MiB at   18.82KiB/s ETA 01:00
[download]  50.6% of    2.24MiB at   18.77KiB/s ETA 01:00
[download]  51.3% of    2.24MiB at   18.78KiB/s ETA 00:59
[download]  52.1% of    2.24MiB at   18.84KiB/s ETA 00:58
[download]  53.1% of    2.24MiB at   18.73KiB/s ETA 00:57
[download]  53.8% of    2.24MiB at   18.95KiB/s ETA 00:55
[download]  55.0% of    2.24MiB at   18.87KiB/s ETA 00:54
[download]  55.7% of    2.24MiB at   18.88KiB/s ETA 00:53
[download]  56.6% of    2.24MiB at   18.93KiB/s ETA 00:52
[download]  57.6% of    2.24MiB at   18.79KiB/s ETA 00:51
[download]  58.2% of    2.24MiB at   18.76KiB/s ETA 00:51
[download]  58.9% of    2.24MiB at   18.77KiB/s ETA 00:50
[download]  59.8% of    2.24MiB at   18.81KiB/s ETA 00:49
[download]  60.7% of    2.24MiB at   18.90KiB/s ETA 00:47
[download]  61.9% of    2.24MiB at   18.82KiB/s ETA 00:46
[download]  62.6% of    2.24MiB at   18.83KiB/s ETA 00:45
[download]  63.4% of    2.24MiB at   18.85KiB/s ETA 00:44
[download]  64.3% of    2.24MiB at   18.74KiB/s ETA 00:43
[download]  64.9% of    2.24MiB at   18.91KiB/s ETA 00:42
[download]  66.1% of    2.24MiB at   18.83KiB/s ETA 00:41
[download]  66.7% of    2.24MiB at   18.80KiB/s ETA 00:40
[download]  67.5% of    2.24MiB at   18.82KiB/s ETA 00:39
[download]  68.4% of    2.24MiB at   18.88KiB/s ETA 00:38
[download]  69.4% of    2.24MiB at   18.79KiB/s ETA 00:37
[download]  70.1% of    2.24MiB at   18.78KiB/s ETA 00:36
[download]  70.8% of    2.24MiB at   18.80KiB/s ETA 00:35
[download]  71.8% of    2.24MiB at   18.86KiB/s ETA 00:34
[download]  72.8% of    2.24MiB at   18.78KiB/s ETA 00:33
[download]  73.5% of    2.24MiB at   18.74KiB/s ETA 00:32
[download]  74.1% of    2.24MiB at   18.73KiB/s ETA 00:31
[download]  74.9% of    2.24MiB at   18.78KiB/s ETA 00:30
[download]  76.0% of    2.24MiB at   18.85KiB/s ETA 00:29
[download]  77.1% of    2.24MiB at   18.78KiB/s ETA 00:27
[download]  77.7% of    2.24MiB at   18.78KiB/s ETA 00:27
[download]  78.6% of    2.24MiB at   18.81KiB/s ETA 00:26
[download]  79.5% of    2.24MiB at   18.85KiB/s ETA 00:24
[download]  80.6% of    2.24MiB at   18.78KiB/s ETA 00:23
[download]  81.2% of    2.24MiB at   18.76KiB/s ETA 00:22
[download]  81.9% of    2.24MiB at   18.77KiB/s ETA 00:22
[download]  82.8% of    2.24MiB at   18.80KiB/s ETA 00:20
[download]  83.8% of    2.24MiB at   18.87KiB/s ETA 00:19
[download]  84.9% of    2.24MiB at   18.81KiB/s ETA 00:18
[download]  85.6% of    2.24MiB at   18.82KiB/s ETA 00:17
[download]  86.5% of    2.24MiB at   18.85KiB/s ETA 00:16
[download]  87.5% of    2.24MiB at   18.77KiB/s ETA 00:15
[download]  88.1% of    2.24MiB at   18.75KiB/s ETA 00:14
[download]  88.8% of    2.24MiB at   18.76KiB/s ETA 00:13
[download]  89.7% of    2.24MiB at   18.79KiB/s ETA 00:12
[download]  90.7% of    2.24MiB at   18.84KiB/s ETA 00:11
[download]  91.8% of    2.24MiB at   18.78KiB/s ETA 00:10
[download]  92.4% of    2.24MiB at   18.77KiB/s ETA 00:09
[download]  93.2% of    2.24MiB at   18.80KiB/s ETA 00:08
[download]  94.1% of    2.24MiB at   18.85KiB/s ETA 00:07
[download]  95.3% of    2.24MiB at   18.79KiB/s ETA 00:05
[download]  95.9% of    2.24MiB at   18.79KiB/s ETA 00:04
[download]  96.8% of    2.24MiB at   18.81KiB/s ETA 00:03
[download]  97.7% of    2.24MiB at   18.85KiB/s ETA 00:02
[download]  98.8% of    2.24MiB at   18.79KiB/s ETA 00:01
[download]  99.4% of    2.24MiB at   18.78KiB/s ETA 00:00
[download] 100.0% of    2.24MiB at   18.87KiB/s ETA 00:00
[download] 100% of    2.24MiB in 00:02:01 at 18.85KiB/s  
```

</details>

## Notes

* MP4 and MP3 work fine.
* The previous version work fine with WEBM.

### LINKED ISSUE #173: Pressing Enter in the 'Add Download' dialog should validate URL, and ESC should "go back"
Since the only purpose of the 'Add Download' dialog is to validate the URL, it makes sense that pressing <kbd>Enter</kbd> in the URL should have the same effect as clicking the 'Validate' button. Pressing <kbd>Enter</kbd> again (after the URL is validated successfully) should start the download process (i.e. same effect as the 'Download' button).

Regarding <kbd>ESC</kbd>, pressing it before the URL is validated should close or hide the 'Add Download' dialog, and pressing it after the URL is validated successfully should restore the 'Add Download' dialog to blank (i.e. same effect as the 'Back' button).

### PR DESCRIPTION
**Pull request by nlogozzo**
Closes #114 
Closes #152 
Closes #129 
Closes #130 
Closes #173 
Closes #156

## TODO
- [x] WinUI
- [x] GNOME

### CODE REVIEW

**Comment by fsobolev** [comment]
Later I want to change the row design a bit that will fix all issues that I found with this PR. I will add changes here, if you don't mind.
Also when we were moving to GTK 4.10 I forgot that ShowURI is deprecated now too.

**Comment by nlogozzo** [comment]
> Later I want to change the row design a bit that will fix all issues that I found with this PR. I will add changes here, if you don't mind.

Go ahead  :)

> Also when we were moving to GTK 4.10 I forgot that ShowURI is deprecated now too.

We could use the new functions in the PR that will wrap everything in g_main_context_iteration to fix #130 

Or we could just do everything here, I don't mind.

**Comment by nlogozzo** [comment]
Ok i wrapped everything that needed in `g_main_context_invoke` to fix gtk crashes :)

**Comment by nlogozzo** [comment]
> Also when we were moving to GTK 4.10 I forgot that ShowURI is deprecated now too.

Committed replacement of `Gtk.Functions.ShowUri()` with `gtk_file_launcher_launch()`.

**Pull request merged**
