### PR TITLE
Edit on download.cpp

### PR DESCRIPTION
**Pull request by fawaz006**
Meow

### CODE REVIEW

**Comment by fsobolev** [comment]
I agree that "--embed-chapters" is a good addition, but "--write-description"? It's usually not needed by most users I think. @nlogozzo, what about implementing this as an option?

**Comment by nlogozzo** [comment]
What does the `write-description` flag do? Just writes the description of the video on the tag? I think that would be valid to have since it is metadata on the video. However sometimes descriptions are long and useless.

**Comment by fawaz006** [comment]
> What does the write-description flag do? Just writes the description of the video on the tag?

Yeah, even it might not be very useful, but it is under the “Metadata” option anyway.

**Comment by fsobolev** [comment]
> What does the `write-description` flag do? Just writes the description of the video on the tag? I think that would be valid to have since it is metadata on the video. However sometimes descriptions are long and useless.

No, not in the tag, it creates `*.description` text file. That's why I'm against it.

**Comment by fawaz006** [comment]
> No, not in the tag, it creates *.description text file. That's why I'm against it.

I was thinking it's just writes the description of the video on the tag
it's look, there are no need to it👍

**Comment by nlogozzo** [comment]
Oh if it creates an extra file then yeah we don't need it. Is there an --embed-description flag of some kind?

**Comment by fsobolev** [comment]
I don't see anything like this in yt-dlp docs. But actually, it seems we don't need `--embed-chapters` since `--embed-metadata` already includes it:
```
--embed-metadata                Embed metadata to the video file. Also
                                embeds chapters/infojson if present unless
                                --no-embed-chapters/--no-embed-info-json are
                                used (Alias: --add-metadata)
```

**Comment by nlogozzo** [comment]
Oh. So then this PR does nothing essentially?

**Comment by fsobolev** [comment]
Sadly, yes 😢

**Comment by fawaz006** [comment]
Yeah, I checked it and it's already embed
image

**Pull request closed without merging**
